# Generated by Django 3.2.9 on 2021-11-15 20:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_number', models.CharField(max_length=10, unique=True)),
                ('customer_surname', models.CharField(max_length=40)),
                ('complaint_category', models.CharField(max_length=100)),
                ('date_logged', models.DateTimeField()),
                ('breach_date', models.DateTimeField()),
                ('welcome_email', models.BooleanField()),
                ('customer_contacted', models.BooleanField()),
                ('holding_correspondence', models.BooleanField()),
                ('outstanding_actions', models.BooleanField()),
                ('latest_update', models.TextField(max_length=250, unique=True)),
                ('case_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_logged'],
            },
        ),
    ]
