# Generated by Django 3.2.9 on 2021-11-16 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allicatorComplaints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='slug',
            field=models.SlugField(max_length=10, null=True, unique=True),
        ),
    ]
