# Generated by Django 3.2.9 on 2021-11-16 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allicatorComplaints', '0002_complaint_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='breach_date',
        ),
    ]
