# Generated by Django 3.2.9 on 2021-11-17 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allicatorComplaints', '0003_remove_complaint_breach_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='date_logged',
            field=models.DateField(),
        ),
    ]
