# Generated by Django 3.2.9 on 2021-11-17 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allicatorComplaints', '0004_alter_complaint_date_logged'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complaint',
            options={'ordering': ['date_logged']},
        ),
    ]
