# Generated by Django 3.2.9 on 2021-11-23 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allicatorComplaints', '0005_alter_complaint_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='latest_update',
            field=models.TextField(max_length=250),
        ),
    ]
